[package]
name = "marrakech"
version = "0.1.0"
authors = ["Ahmed Hussein amhussein4@gmail.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[profile.dev]
#panic = "abort"

[dependencies]

